version: '3.8'

services:
  cfp-scout:
    build: .
    container_name: cfp-scout
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Optional: Run once and exit (for manual testing)
    # command: python src/main.py
    
    # Optional: For scheduled runs with cron inside container
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y cron &&
        echo '0 8 * * * cd /app && python src/main.py >> /app/logs/cfp-scout.log 2>&1' | crontab - &&
        cron -f
      "

# Optional: For one-time runs
  cfp-scout-oneshot:
    build: .
    container_name: cfp-scout-oneshot
    env_file: .env
    volumes:
      - ./logs:/app/logs
    command: python src/main.py
    profiles:
      - manual 